set(SOURCE
src/cpu/insts/gen/Xor.cpp
src/cpu/insts/Xor.cpp
src/cpu/insts/gen/Xor.h
src/cpu/insts/gen/Cmp.cpp
src/cpu/insts/Cmp.cpp
src/cpu/insts/gen/Cmp.h
src/cpu/insts/gen/Jo.cpp
src/cpu/insts/Jo.cpp
src/cpu/insts/gen/Jo.h
src/cpu/insts/gen/Jno.cpp
src/cpu/insts/Jno.cpp
src/cpu/insts/gen/Jno.h
src/cpu/insts/gen/Jb.cpp
src/cpu/insts/Jb.cpp
src/cpu/insts/gen/Jb.h
src/cpu/insts/gen/Jnb.cpp
src/cpu/insts/Jnb.cpp
src/cpu/insts/gen/Jnb.h
src/cpu/insts/gen/Jz.cpp
src/cpu/insts/Jz.cpp
src/cpu/insts/gen/Jz.h
src/cpu/insts/gen/Jnz.cpp
src/cpu/insts/Jnz.cpp
src/cpu/insts/gen/Jnz.h
src/cpu/insts/gen/Jbe.cpp
src/cpu/insts/Jbe.cpp
src/cpu/insts/gen/Jbe.h
src/cpu/insts/gen/Jnbe.cpp
src/cpu/insts/Jnbe.cpp
src/cpu/insts/gen/Jnbe.h
src/cpu/insts/gen/Js.cpp
src/cpu/insts/Js.cpp
src/cpu/insts/gen/Js.h
src/cpu/insts/gen/Jns.cpp
src/cpu/insts/Jns.cpp
src/cpu/insts/gen/Jns.h
src/cpu/insts/gen/Jp.cpp
src/cpu/insts/Jp.cpp
src/cpu/insts/gen/Jp.h
src/cpu/insts/gen/Jnp.cpp
src/cpu/insts/Jnp.cpp
src/cpu/insts/gen/Jnp.h
src/cpu/insts/gen/Jl.cpp
src/cpu/insts/Jl.cpp
src/cpu/insts/gen/Jl.h
src/cpu/insts/gen/Jnl.cpp
src/cpu/insts/Jnl.cpp
src/cpu/insts/gen/Jnl.h
src/cpu/insts/gen/Jle.cpp
src/cpu/insts/Jle.cpp
src/cpu/insts/gen/Jle.h
src/cpu/insts/gen/Jnle.cpp
src/cpu/insts/Jnle.cpp
src/cpu/insts/gen/Jnle.h
src/cpu/insts/gen/Mov.cpp
src/cpu/insts/Mov.cpp
src/cpu/insts/gen/Mov.h
src/cpu/insts/gen/Sahf.cpp
src/cpu/insts/Sahf.cpp
src/cpu/insts/gen/Sahf.h
src/cpu/insts/gen/Lahf.cpp
src/cpu/insts/Lahf.cpp
src/cpu/insts/gen/Lahf.h
src/cpu/insts/gen/Test.cpp
src/cpu/insts/Test.cpp
src/cpu/insts/gen/Test.h
src/cpu/insts/gen/Rol.cpp
src/cpu/insts/Rol.cpp
src/cpu/insts/gen/Rol.h
src/cpu/insts/gen/Ror.cpp
src/cpu/insts/Ror.cpp
src/cpu/insts/gen/Ror.h
src/cpu/insts/gen/Rcl.cpp
src/cpu/insts/Rcl.cpp
src/cpu/insts/gen/Rcl.h
src/cpu/insts/gen/Rcr.cpp
src/cpu/insts/Rcr.cpp
src/cpu/insts/gen/Rcr.h
src/cpu/insts/gen/Shl.cpp
src/cpu/insts/Shl.cpp
src/cpu/insts/gen/Shl.h
src/cpu/insts/gen/Shr.cpp
src/cpu/insts/Shr.cpp
src/cpu/insts/gen/Shr.h
src/cpu/insts/gen/Sal.cpp
src/cpu/insts/Sal.cpp
src/cpu/insts/gen/Sal.h
src/cpu/insts/gen/Sar.cpp
src/cpu/insts/Sar.cpp
src/cpu/insts/gen/Sar.h
src/cpu/insts/gen/In.cpp
src/cpu/insts/In.cpp
src/cpu/insts/gen/In.h
src/cpu/insts/gen/Out.cpp
src/cpu/insts/Out.cpp
src/cpu/insts/gen/Out.h
src/cpu/insts/gen/Jmp.cpp
src/cpu/insts/Jmp.cpp
src/cpu/insts/gen/Jmp.h
src/cpu/insts/gen/Jmpf.cpp
src/cpu/insts/Jmpf.cpp
src/cpu/insts/gen/Jmpf.h
src/cpu/insts/Hlt.cpp
src/cpu/insts/gen/Hlt.h
src/cpu/insts/Clc.cpp
src/cpu/insts/gen/Clc.h
src/cpu/insts/Stc.cpp
src/cpu/insts/gen/Stc.h
src/cpu/insts/Cli.cpp
src/cpu/insts/gen/Cli.h
src/cpu/insts/Sti.cpp
src/cpu/insts/gen/Sti.h
src/cpu/insts/Cld.cpp
src/cpu/insts/gen/Cld.h
src/cpu/insts/Std.cpp
src/cpu/insts/gen/Std.h
)
